aggregation: sum
alpha: 0.1
batch_size: 64
ckpt_path: null
diffusion_schedule: original
diffusion_steps: 1000
diffusion_type: blackout
do_test: true
do_train: true
do_valid_only: false
fp16: false
hidden_dim: 256
inference_diffusion_steps: 50
inference_generation_type: binomial
inference_schedule: original
inference_trick: ddim
learning_rate: 0.0002
logger_name: diffusco
lr_scheduler: cosine-decay
n_layers: 12
num_epochs: 50
num_states: 2
num_workers: 16
parallel_sampling: 1
project_name: tsp_diffusion
resume_weight_only: false
save_numpy_heatmap: false
sequential_sampling: 1
sparse_factor: -1
storage_path: ./
task: tsp
test_split: /data/tsp_dataset/tsp50_test_concorde.txt
training_split: /data/tsp_dataset/tsp50_train_concorde.txt
training_split_label_dir: null
two_opt_iterations: 1000
use_activation_checkpoint: false
validation_examples: 8
validation_split: /data/tsp_dataset/tsp50_test_concorde.txt
weight_decay: 0.0001
